apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/nickgamu/dispatcher-service/k8s?ref=main

patchesStrategicMerge:
- patch-env.yml
- patch-resources.yml
- patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: dispatcher-config

images:
- name: dispatcher-service
  newName: ghcr.io/nickgamu/dispatcher-service
  newTag: 71a51039a1c42ec79ade2d3d07d4ca808c60b709

replicas:
- count: 1
  name: dispatcher-service
