polar:
  greeting: Welcome to our book catalog from a production Kubernetes environment synchronized by ArgoCD!
spring:
  config:
    import: configtree:/workspace/secrets/*/

  datasource:
    url: jdbc:postgresql://postgres/polar_catalog
  flyway:
    url: jdbc:postgresql://postgres/polar_order
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak/realms/PolarBookshop